### ISSUE TITLE
Incompatibilities with ljsyscall

### ISSUE THREAD

**Issue by bungle** [daurnimator/luatz#11]
While ljsyscall provides this:
https://github.com/justincormack/ljsyscall/blob/master/syscall/rump/c.lua#L422

This line will error on it:
https://github.com/daurnimator/luatz/blob/master/luatz/gettime.lua#L7

```
gettime.lua:7: attempt to index field 'CLOCK' (a nil value)
```

**Comment by daurnimator** [comment]
Hrm. it should provide that field: https://github.com/justincormack/ljsyscall/blob/178d244a01c1ea33364c7295ac4ae9f73a1fdd52/syscall/linux/constants.lua#L611

**Comment by daurnimator** [comment]
ping @justincormack: is luatz's code correct?

**Comment by justincormack** [comment]
It works for me on Linux. I notice though on OSX I haven't added the `CLOCK` constants and calls, I think they arrived in 10.12, finally... Which platform are you testing on?

**Comment by bungle** [comment]
@justincormack, yeah, the error happened on lastest macOS Sierra.

**Comment by justincormack** [comment]
ah ok, that should be a fairly easy fix

**Comment by justincormack** [comment]
Ok, updated in https://github.com/justincormack/ljsyscall/pull/209 should fix it...

**Comment by daurnimator** [comment]
Thanks @justincormack. @bungle please check that works for you and then close this issue.

**Comment by daurnimator** [comment]
I just added a check in-case this somehow happens again in future.

**Comment by bungle** [comment]
Thank you @daurnimator and @justincormack. Glad that this got fixed quickly. Two great libs to care as bout.
