### ISSUE TITLE
Convertion problems using more than 1GB in Luajit GC64 Mode

### ISSUE THREAD

**Issue by suporteavancado** [daurnimator/luatz#12]
Hi,

There are major problems in converting dates through the LUATZ module when RAM usage exceeds 1GB using the Luajit GC64 mode.
Example: Time zone conversion resulting in dates with years added to 100.
To test it is enough to perform, for example, a loading of a large csv file containing dates and try a time zone convertion.

**Comment by daurnimator** [comment]
Do you have a sample you can upload?

What function(s) are you calling?

Are you sure you're not just having more than 1gb of csv data in memory?

**Comment by daurnimator** [comment]
Closing due to lack of response.
