### ISSUE TITLE
Not normalizing correctly when tt.day<=0

### ISSUE THREAD

**Issue by supernev** [daurnimator/luatz#13]
Lua timetable {year=2017, month=12, day=0} means 2017-11-30
But luatz timetable will normalize to 2017-12-01

The same problem when day<=0.

**Comment by daurnimator** [comment]
Looks like an issue in the year after leap years:
```
> require"luatz.timetable".new(2016,10,0,0,0,0):normalise()
2016-09-29T00:00:00.000
> require"luatz.timetable".new(2017,10,0,0,0,0):normalise()
2017-10-01T00:00:00.000
> require"luatz.timetable".new(2018,10,0,0,0,0):normalise()
2018-09-30T00:00:00.000
```

And turns out one of the existing tests is incorrect, which prevented this from being found earlier.

Pushing fix.

**Comment by supernev** [comment]
Great feedback! Thanks~
