### ISSUE TITLE
Errorless "safe" version

### ISSUE THREAD

**Issue by bungle** [daurnimator/luatz#6]
There are some `error` calls. Would it make any sense to have Lua style `return nil, "error reason"` type API as well or some options?

**Comment by daurnimator** [comment]
```
$ grep -r error
luatz/parse.lua:		error ( "Invalid RFC 3339 timestamp" )
luatz/strftime.lua:			error ( "invalid conversation specifier '%"..locale_modifier..specifier.."'" , 3 )
luatz/timetable.lua:		error ( "bad argument #1 to 'new_from_timestamp' (number expected, got " .. type ( ts ) .. ")" , 2 )
luatz/tzfile.lua:		error ( "Unsupported version" )
luatz/tzinfo.lua:		error ( "Too many transitions in a 2 day period" )
```

Which of these errors would you want to not have actually throw an error; they are almost all about invalid input.

**Comment by bungle** [comment]
`parse` could return `nil, "Invalid RFC 3339 timestamp"` instead of throwing `error`. I have not checked others, but this came to my mind.

**Comment by daurnimator** [comment]
I'm happy to fix the `parse` in-particular.
