### ISSUE TITLE
Possible optimisation for normalise(...) function in timetable.lua

### ISSUE THREAD

**Issue by maciejmiklas** [daurnimator/luatz#8]
There is this main function that calculates year, month and day. For large days it produces large amount of iterations. You can speed it up, by calculating offset for #sec and #year.

Define new function:

```
function year_offset(ts)
	local year, offset
	if ts >= 1735689600 then
		year, offset = 2025, 1735689600 -- 1.1.2015
	
	elseif ts >= 1577836800 then
		year, offset = 2020, 1577836800 -- 1.1.2020
	
	elseif ts >= 1420070400 then
		year, offset = 2015, 1420070400 -- 1.1.2015
	
	elseif ts >= 1262304000 then
		year, offset = 2010, 1262304000 -- 1.1.2010
	
	elseif ts >= 946684800 then
		year, offset = 2000, 946684800 -- 1.1.2000
	
	elseif ts >= 631152000 then
		year, offset = 1990, 631152000 -- 1.1.1990
	
	elseif ts >= 315532800 then
		year, offset = 1980, 315532800 -- 1.1.1980
	
	else
		year, offset = 1970, 0
	end
	return year, offset
end
```

and call it here:

```
local function normalise ( year , month , day , hour , min , sec )
    year, offset = year_offset(sec)
    sec = sec - offset
    .....
```

In this case we are shifting #sec to know pre-calculated year and instead of starting on 1970 we start on closest year to given #sec

**Comment by daurnimator** [comment]
I don't like the idea of use a if/else tree for this.
I think the correct solution is to upper/lower bounds (via multiplication/division and assuming all years are non-leap/leap years) and then doing a small number of iterations to get a correction.
Someone just needs to sit down and figure out the math.

**Comment by maciejmiklas** [comment]
yes - this is better solution
