### ISSUE TITLE
Issue with strftime

### ISSUE THREAD

**Issue by vadi2** [daurnimator/luatz#9]
Not sure why this isn't working:

```
luatz.strftime.strftime("%a, %d %b %Y %H:%M:%S %Z", luatz.parse.rfc_3339("2016-10-03T07:06:31.567Z"))
/usr/local/share/lua/5.1/luatz/strftime.lua:194: bad argument #2 to 'strformat' (string expected, got nil)
stack traceback:
	[C]: in function 'strformat'
	/usr/local/share/lua/5.1/luatz/strftime.lua:194: in function </usr/local/share/lua/5.1/luatz/strftime.lua:191>
	[C]: in function 'gsub'
	/usr/local/share/lua/5.1/luatz/strftime.lua:191: in function 'strftime'
	stdin:1: in main chunk
	[C]: ?
```

**Comment by daurnimator** [comment]
The timetable object returned by `parse.rfc_3339` has not been normalised, and hence doesn't have the `wday` (weekday) field populated.
Instead, try: 
```
> return luatz.strftime.strftime("%a, %d %b %Y %H:%M:%S %Z", luatz.parse.rfc_3339("2016-10-03T07:06:31.567Z"):normalise())
Mon, 03 Oct 2016 07:06:31 GMT
```

**Comment by vadi2** [comment]
Thanks, that worked.

**Comment by daurnimator** [comment]
Feel free to suggest any documentation changes that may make this more obvious.

**Comment by vadi2** [comment]
It would be really nice if documentation was available online, with a link to it from the README. strftime isn't included in the documentation, so adding it in with an example on how to convert from another timeformat would be great.
